import type { GuideData } from './shared'

export const guides: GuideData[] = [
  {
    slug: 'summarize-articles',
    title: 'How to Summarize Articles with AI',
    keyword: 'summarize articles with AI Chrome extension',
    h1: 'How to Summarize Articles with Prophet AI',
    description: 'Learn how to instantly summarize any article, blog post, or news story using Prophet AI in your Chrome side panel. Save hours of reading time.',
    difficulty: 'beginner',
    estimatedTime: '2 minutes',
    steps: [
      { title: 'Open the article you want to summarize', description: 'Navigate to any article, blog post, or news story in Chrome. Prophet works on any webpage with text content.' },
      { title: 'Open Prophet in the side panel', description: 'Click the Prophet icon in your Chrome toolbar or use the keyboard shortcut to open the AI side panel alongside the article.' },
      { title: 'Ask for a summary', description: 'Type a prompt like "Summarize this article in 3 bullet points" or "Give me the key takeaways from this page." Prophet reads the page content automatically.' },
      { title: 'Refine or ask follow-up questions', description: 'Ask Prophet to elaborate on specific points, simplify the language, or translate the summary into another language.' },
    ],
    proTips: [
      'Use "Summarize in 3 sentences" for quick overviews, or "Detailed summary with key statistics" for thorough analysis.',
      'Ask Prophet to compare the article with information you already know by providing context in your prompt.',
      'For academic papers, try "Summarize the methodology, findings, and limitations separately."',
    ],
    examplePrompts: [
      'Summarize this article in 3 bullet points.',
      'What are the key arguments made in this article?',
      'Give me a one-paragraph summary suitable for sharing with my team.',
      'What data or statistics does this article cite?',
    ],
    relatedSlugs: ['research-topics', 'extract-data', 'translate-webpages'],
  },
  {
    slug: 'fill-out-forms',
    title: 'How to Auto-Fill Forms with AI',
    keyword: 'auto fill forms AI Chrome extension',
    h1: 'How to Fill Out Forms Faster with Prophet AI',
    description: 'Use Prophet AI to automatically fill out web forms, applications, and surveys. Let the AI agent handle repetitive form filling across any website.',
    difficulty: 'intermediate',
    estimatedTime: '5 minutes',
    steps: [
      { title: 'Navigate to the form', description: 'Open the webpage containing the form you need to fill out. Prophet works with contact forms, applications, surveys, checkout forms, and more.' },
      { title: 'Open Prophet and describe what to fill', description: 'Open the side panel and tell Prophet what information to enter. For example: "Fill out this contact form with my name John Smith, email john@example.com."' },
      { title: 'Review the agent actions', description: 'Prophet uses browser automation to identify form fields and fill them in. Watch each action in the chat log as the agent interacts with the page.' },
      { title: 'Verify and submit', description: 'Review the filled form before submitting. Prophet does not automatically submit forms unless you explicitly ask it to.' },
      { title: 'Save common templates', description: 'Keep a text file with your frequently used form data. Paste it into Prophet for quick reuse across different forms.' },
    ],
    proTips: [
      'Be specific about field values. Instead of "fill the form," say "fill the first name field with John and the last name field with Smith."',
      'For multi-step forms, guide Prophet through each step: "Fill out step 1, then click Next."',
    ],
    examplePrompts: [
      'Fill out this contact form with: Name: Jane Doe, Email: jane@company.com, Message: I am interested in a demo.',
      'Complete this registration form using the information I provide below.',
      'Fill all required fields on this application form. Ask me for any information you need.',
    ],
    relatedSlugs: ['automate-data-entry', 'write-emails-faster'],
  },
  {
    slug: 'write-emails-faster',
    title: 'How to Write Emails Faster with AI',
    keyword: 'write emails faster AI Chrome extension',
    h1: 'How to Write Emails Faster with Prophet AI',
    description: 'Draft, reply to, and improve emails directly in your browser with Prophet AI. Works with Gmail, Outlook, and any web-based email client.',
    difficulty: 'beginner',
    estimatedTime: '3 minutes',
    steps: [
      { title: 'Open your email client', description: 'Navigate to Gmail, Outlook, or any web-based email client in Chrome. Open the email you want to reply to, or start composing a new message.' },
      { title: 'Open Prophet in the side panel', description: 'Click the Prophet icon to open the AI assistant alongside your email. Prophet can read the current page context.' },
      { title: 'Describe the email you need', description: 'Tell Prophet what kind of email to write. Provide the tone, key points, and recipient context. For replies, Prophet can read the original email on the page.' },
      { title: 'Copy or paste the draft', description: 'Review the generated email, make any adjustments in the chat, then copy the final version into your email compose window.' },
    ],
    proTips: [
      'Specify the tone: "Write a professional but friendly reply" or "Draft a formal follow-up email."',
      'For replies, say "Read the email on this page and write a reply that addresses each of their questions."',
      'Ask Prophet to shorten or lengthen the draft: "Make this more concise" or "Add more detail about the timeline."',
    ],
    examplePrompts: [
      'Draft a professional reply to this email that confirms the meeting time and asks about the agenda.',
      'Write a cold outreach email introducing our product to a potential client.',
      'Make this email more concise while keeping the key points.',
      'Write a follow-up email for someone who has not responded in a week.',
    ],
    relatedSlugs: ['fill-out-forms', 'summarize-articles', 'translate-webpages'],
  },
  {
    slug: 'research-topics',
    title: 'How to Research Topics with AI',
    keyword: 'research topics AI Chrome extension',
    h1: 'How to Research Any Topic with Prophet AI',
    description: 'Use Prophet AI to research topics across multiple web pages, synthesize information, and generate structured notes without leaving your browser.',
    difficulty: 'intermediate',
    estimatedTime: '10 minutes',
    steps: [
      { title: 'Open your first source', description: 'Navigate to an article, report, or webpage related to your research topic. This will be the starting point for your research session.' },
      { title: 'Ask Prophet to analyze the page', description: 'Open the side panel and ask Prophet to extract key information. For example: "What are the main points about renewable energy on this page?"' },
      { title: 'Navigate to additional sources', description: 'Open new tabs with additional sources. Prophet can help you navigate: "Search Google for recent studies on solar panel efficiency."' },
      { title: 'Synthesize across sources', description: 'Ask Prophet to combine findings: "Based on the pages I have shown you, summarize the current state of solar panel technology."' },
      { title: 'Generate structured output', description: 'Ask Prophet to format your research: "Create an outline with sources for a report on this topic" or "Generate a comparison table."' },
    ],
    proTips: [
      'Use multiple tabs and switch between them. Prophet can read whichever page is currently active.',
      'Ask Prophet to identify gaps in your research: "What aspects of this topic have I not covered yet?"',
      'Request specific output formats: outlines, bullet points, comparison tables, or annotated bibliographies.',
    ],
    examplePrompts: [
      'Summarize the key findings from this research paper.',
      'What are the main arguments for and against this position based on this page?',
      'Create a comparison table of the three products reviewed on this page.',
      'Generate an outline for a blog post based on the information on this page.',
    ],
    relatedSlugs: ['summarize-articles', 'extract-data', 'compare-products'],
  },
  {
    slug: 'debug-code',
    title: 'How to Debug Code with AI',
    keyword: 'debug code AI Chrome extension',
    h1: 'How to Debug Code with Prophet AI',
    description: 'Use Prophet AI to debug code on GitHub, Stack Overflow, or any code-sharing platform. Get explanations, fixes, and suggestions without leaving your browser.',
    difficulty: 'advanced',
    estimatedTime: '5 minutes',
    steps: [
      { title: 'Open the code in your browser', description: 'Navigate to the code on GitHub, GitLab, Stack Overflow, CodePen, or any platform where code is displayed. Prophet reads the visible page content.' },
      { title: 'Ask Prophet to analyze the code', description: 'Open the side panel and ask: "What does this code do?" or "Find bugs in this code." Prophet reads the code from the page context.' },
      { title: 'Describe the problem', description: 'Provide error messages, unexpected behavior, or test failures. The more context you give, the better the debugging assistance.' },
      { title: 'Review suggested fixes', description: 'Prophet will explain the issue and suggest corrections. You can ask follow-up questions to understand the root cause.' },
      { title: 'Ask for improvements', description: 'Beyond fixing bugs, ask Prophet to optimize performance, improve readability, or add error handling to the code.' },
    ],
    proTips: [
      'Paste error messages directly into the chat for more accurate debugging.',
      'Ask Prophet to explain the fix: "Why does this change solve the problem?"',
      'For complex issues, break the problem down: "First explain what line 42 does, then tell me why it might fail."',
    ],
    examplePrompts: [
      'Explain what this code does and identify any potential bugs.',
      'I am getting this error: [paste error]. What is causing it in the code on this page?',
      'How can I optimize the performance of this function?',
      'Rewrite this code with proper error handling and TypeScript types.',
    ],
    relatedSlugs: ['review-pull-requests', 'research-topics'],
  },
  {
    slug: 'review-pull-requests',
    title: 'How to Review Pull Requests with AI',
    keyword: 'review pull requests AI Chrome extension',
    h1: 'How to Review Pull Requests with Prophet AI',
    description: 'Speed up code reviews by using Prophet AI to analyze pull requests on GitHub. Get summaries, find issues, and understand changes faster.',
    difficulty: 'advanced',
    estimatedTime: '10 minutes',
    steps: [
      { title: 'Open the pull request on GitHub', description: 'Navigate to the pull request page on GitHub. Make sure you are on the "Files changed" tab to see the diff.' },
      { title: 'Ask Prophet to summarize the changes', description: 'Open the side panel and ask: "Summarize the changes in this pull request." Prophet will read the diff and provide an overview.' },
      { title: 'Request a detailed review', description: 'Ask Prophet to look for specific issues: "Are there any potential bugs, security vulnerabilities, or performance problems in these changes?"' },
      { title: 'Check specific files', description: 'Scroll to specific files in the diff and ask targeted questions: "What does this new function do?" or "Is this error handling sufficient?"' },
      { title: 'Generate review comments', description: 'Ask Prophet to draft review comments: "Write a constructive review comment about the missing input validation in this file."' },
      { title: 'Navigate through large PRs', description: 'For large pull requests, ask Prophet to prioritize: "Which files in this PR have the most significant changes?"' },
    ],
    proTips: [
      'Start with "Summarize this PR in one paragraph" to get a quick overview before diving into details.',
      'Ask about test coverage: "Does this PR include tests for the new functionality?"',
    ],
    examplePrompts: [
      'Summarize the changes in this pull request.',
      'Are there any potential bugs or security issues in these code changes?',
      'Write a constructive review comment for this function.',
      'Does this code follow best practices for error handling?',
    ],
    relatedSlugs: ['debug-code', 'research-topics'],
  },
  {
    slug: 'translate-webpages',
    title: 'How to Translate Web Pages with AI',
    keyword: 'translate web pages AI Chrome extension',
    h1: 'How to Translate Web Pages with Prophet AI',
    description: 'Translate entire web pages or specific sections using Prophet AI. Get natural, context-aware translations that outperform machine translation.',
    difficulty: 'beginner',
    estimatedTime: '3 minutes',
    steps: [
      { title: 'Open the foreign-language page', description: 'Navigate to the web page you want to translate. Prophet works with any language that Claude supports.' },
      { title: 'Open Prophet and request translation', description: 'Open the side panel and ask: "Translate this page to English" or specify any target language.' },
      { title: 'Get section-specific translations', description: 'For long pages, ask Prophet to translate specific sections: "Translate the pricing table on this page" or "What does the second paragraph say in English?"' },
      { title: 'Ask for context and nuance', description: 'Unlike basic translators, Prophet can explain cultural context, idioms, and nuances: "What does this phrase actually mean in context?"' },
    ],
    proTips: [
      'Prophet provides more natural translations than word-for-word tools because Claude understands context and idioms.',
      'Ask for translations at different formality levels: "Translate this casually" vs "Translate this formally."',
      'For technical content, specify the domain: "Translate this legal document" or "Translate this medical article."',
    ],
    examplePrompts: [
      'Translate the main content of this page into English.',
      'What does this page say? Summarize it in English.',
      'Translate the product description on this page into Spanish.',
      'Explain the cultural context of the idiom used in the second paragraph.',
    ],
    relatedSlugs: ['summarize-articles', 'write-emails-faster', 'extract-data'],
  },
  {
    slug: 'compare-products',
    title: 'How to Compare Products with AI',
    keyword: 'compare products AI Chrome extension',
    h1: 'How to Compare Products with Prophet AI',
    description: 'Use Prophet AI to compare products, services, and pricing across different websites. Get structured comparison tables and recommendations.',
    difficulty: 'intermediate',
    estimatedTime: '10 minutes',
    steps: [
      { title: 'Open the first product page', description: 'Navigate to the product page for the first item you want to compare. This could be on Amazon, a brand website, or any e-commerce platform.' },
      { title: 'Ask Prophet to extract product details', description: 'Open the side panel and ask: "Extract the key specs, price, and features of this product." Prophet reads the page and structures the data.' },
      { title: 'Navigate to competing products', description: 'Open tabs with competing products. Switch between tabs and ask Prophet to extract details from each one.' },
      { title: 'Request a comparison', description: 'Ask Prophet to generate a comparison: "Compare the products I have shown you in a table with price, key features, and pros/cons."' },
      { title: 'Get a recommendation', description: 'Provide your priorities and ask for a recommendation: "Which product is best for someone who prioritizes battery life and portability?"' },
    ],
    proTips: [
      'Be specific about comparison criteria: "Compare on price, battery life, weight, and display quality."',
      'Ask Prophet to factor in reviews: "Based on the reviews on this page, what are common complaints about this product?"',
    ],
    examplePrompts: [
      'Extract the price, key features, and specifications from this product page.',
      'Create a comparison table of these two products based on the pages I showed you.',
      'What are the pros and cons of this product based on the reviews on this page?',
      'Which of these products offers the best value for money?',
    ],
    relatedSlugs: ['extract-data', 'research-topics', 'summarize-articles'],
  },
  {
    slug: 'extract-data',
    title: 'How to Extract Data from Web Pages',
    keyword: 'extract data from web pages AI Chrome',
    h1: 'How to Extract Data from Web Pages with Prophet AI',
    description: 'Extract structured data from any web page using Prophet AI. Convert tables, lists, and unstructured content into clean, organized formats.',
    difficulty: 'intermediate',
    estimatedTime: '5 minutes',
    steps: [
      { title: 'Open the page with the data', description: 'Navigate to the web page containing the data you need. This could be a table, a list of items, contact information, pricing data, or any structured content.' },
      { title: 'Ask Prophet to extract specific data', description: 'Open the side panel and describe what you need: "Extract all email addresses from this page" or "Pull the pricing data from this table."' },
      { title: 'Specify the output format', description: 'Tell Prophet how you want the data formatted: "Give me this as a CSV" or "Format this as a JSON array" or "Create a markdown table."' },
      { title: 'Handle multi-page data', description: 'For data spread across pages, ask Prophet to help navigate: "Scroll down and extract all items from this list" or navigate through pagination.' },
    ],
    proTips: [
      'Specify the exact format you need upfront: CSV, JSON, markdown table, or plain text list.',
      'For large datasets, extract in batches: "Get the first 20 items, then I will scroll down for more."',
      'Ask Prophet to clean the data: "Extract the prices and remove currency symbols, giving me just the numbers."',
    ],
    examplePrompts: [
      'Extract all the names and email addresses from this contact page as a CSV.',
      'Pull the pricing information from this page and format it as a markdown table.',
      'Extract every link on this page with its anchor text.',
      'Get all the product names and prices from this catalog page as JSON.',
    ],
    relatedSlugs: ['compare-products', 'automate-data-entry', 'research-topics'],
  },
  {
    slug: 'automate-data-entry',
    title: 'How to Automate Data Entry with AI',
    keyword: 'automate data entry AI Chrome extension',
    h1: 'How to Automate Data Entry with Prophet AI',
    description: 'Automate repetitive data entry tasks across web applications using Prophet AI browser automation. Save hours on CRM updates, spreadsheet entries, and form submissions.',
    difficulty: 'advanced',
    estimatedTime: '15 minutes',
    steps: [
      { title: 'Open the target application', description: 'Navigate to the web application where you need to enter data: a CRM, admin dashboard, spreadsheet tool, or any web-based form.' },
      { title: 'Provide the data to enter', description: 'Paste the data directly into the Prophet chat. You can provide it as a list, CSV, or just describe what needs to be entered.' },
      { title: 'Instruct Prophet to automate the entry', description: 'Tell Prophet to fill in the data: "Enter each of these contacts into the form on this page. After filling each one, click Submit and then click Add New."' },
      { title: 'Monitor the automation', description: 'Watch as Prophet fills fields, clicks buttons, and navigates through the workflow. Each action appears in the chat log.' },
      { title: 'Handle errors and edge cases', description: 'If Prophet encounters an issue (field not found, unexpected popup), it will pause and ask for guidance. Provide instructions to continue.' },
      { title: 'Verify the results', description: 'After automation completes, review the entered data to confirm accuracy. Check for any entries that may need manual correction.' },
    ],
    proTips: [
      'Start with a single entry to verify the workflow before automating the full batch.',
      'Use Sonnet or Opus models for complex multi-step data entry tasks that require reasoning about page changes.',
    ],
    examplePrompts: [
      'Enter the following 5 contacts into this CRM form, clicking Submit after each: [paste data].',
      'Fill out this spreadsheet row with the data from my clipboard.',
      'Update each of these records: change the status field from Pending to Approved.',
    ],
    relatedSlugs: ['fill-out-forms', 'extract-data'],
  },
]

export function getGuideBySlug(slug: string): GuideData | undefined {
  return guides.find((g) => g.slug === slug)
}

export function getAllGuideSlugs(): string[] {
  return guides.map((g) => g.slug)
}
