import type { IntegrationData } from './shared'

export const integrations: IntegrationData[] = [
  {
    slug: 'github',
    platform: 'GitHub',
    title: 'Prophet AI for GitHub',
    keyword: 'AI Chrome extension for GitHub',
    h1: 'Use Prophet AI on GitHub',
    description: 'Supercharge your GitHub workflow with Prophet AI. Review pull requests, understand code, debug issues, and navigate repositories faster with AI assistance in your Chrome side panel.',
    tasks: [
      'Summarize pull request changes and generate review comments',
      'Explain complex code in any repository file',
      'Find bugs and suggest fixes in diffs',
      'Navigate large codebases and understand project structure',
      'Draft issue descriptions and responses from context',
      'Compare branches and understand merge conflicts',
    ],
    examplePrompts: [
      'Summarize the changes in this pull request.',
      'Explain what this function does and identify any potential issues.',
      'Write a detailed issue description for the bug I am seeing on this page.',
      'What files in this repository are related to authentication?',
    ],
  },
  {
    slug: 'google-docs',
    platform: 'Google Docs',
    title: 'Prophet AI for Google Docs',
    keyword: 'AI Chrome extension for Google Docs',
    h1: 'Use Prophet AI with Google Docs',
    description: 'Enhance your writing in Google Docs with Prophet AI. Draft content, edit for clarity, restructure documents, and get feedback without leaving your document.',
    tasks: [
      'Draft new sections or entire documents from an outline',
      'Edit existing text for grammar, clarity, and tone',
      'Restructure and reorganize document content',
      'Summarize long documents into executive summaries',
      'Translate document content into other languages',
      'Generate tables of contents and document outlines',
    ],
    examplePrompts: [
      'Read this document and suggest improvements to the introduction.',
      'Rewrite this paragraph to be more concise and professional.',
      'Generate an executive summary of this document.',
      'Translate the selected section into French.',
    ],
  },
  {
    slug: 'gmail',
    platform: 'Gmail',
    title: 'Prophet AI for Gmail',
    keyword: 'AI Chrome extension for Gmail',
    h1: 'Use Prophet AI with Gmail',
    description: 'Write, reply to, and manage emails faster with Prophet AI in Gmail. Draft professional responses, summarize email threads, and handle your inbox efficiently.',
    tasks: [
      'Draft replies that address every point in the original email',
      'Write new emails with the right tone and structure',
      'Summarize long email threads into key action items',
      'Translate incoming emails from other languages',
      'Proofread and improve email drafts before sending',
    ],
    examplePrompts: [
      'Write a professional reply to this email accepting the meeting invitation.',
      'Summarize this email thread and list the action items.',
      'Draft a follow-up email for a proposal I sent last week.',
      'Make this email more concise while keeping all the important details.',
    ],
  },
  {
    slug: 'notion',
    platform: 'Notion',
    title: 'Prophet AI for Notion',
    keyword: 'AI Chrome extension for Notion',
    h1: 'Use Prophet AI with Notion',
    description: 'Boost your Notion productivity with Prophet AI. Create pages, organize databases, draft content, and manage your workspace with AI assistance from the Chrome side panel.',
    tasks: [
      'Draft new Notion pages from brief descriptions',
      'Summarize and reorganize existing page content',
      'Generate templates for recurring workflows',
      'Extract and structure data from other web pages into Notion format',
      'Create meeting notes, project briefs, and documentation',
      'Help navigate and search within large Notion workspaces',
    ],
    examplePrompts: [
      'Create a project brief template based on the structure of this page.',
      'Summarize this Notion page into bullet points.',
      'Draft a meeting agenda for a product review based on this project page.',
      'Help me reorganize this page into a clearer structure.',
    ],
  },
  {
    slug: 'linkedin',
    platform: 'LinkedIn',
    title: 'Prophet AI for LinkedIn',
    keyword: 'AI Chrome extension for LinkedIn',
    h1: 'Use Prophet AI on LinkedIn',
    description: 'Create engaging LinkedIn posts, craft connection messages, and optimize your profile with Prophet AI. Stand out on LinkedIn with AI-powered content creation.',
    tasks: [
      'Write engaging LinkedIn posts from brief ideas',
      'Craft personalized connection request messages',
      'Optimize your LinkedIn profile sections for visibility',
      'Draft thoughtful comments on other people\'s posts',
      'Summarize articles shared on LinkedIn',
      'Create professional responses to recruiter messages',
    ],
    examplePrompts: [
      'Write a LinkedIn post about my experience launching a new product.',
      'Draft a connection request message to a hiring manager at this company.',
      'Improve my LinkedIn headline and summary to attract more recruiters.',
      'Write a thoughtful comment on this post.',
    ],
  },
  {
    slug: 'reddit',
    platform: 'Reddit',
    title: 'Prophet AI for Reddit',
    keyword: 'AI Chrome extension for Reddit',
    h1: 'Use Prophet AI on Reddit',
    description: 'Navigate Reddit more efficiently with Prophet AI. Summarize long threads, draft replies, research topics across subreddits, and extract useful information.',
    tasks: [
      'Summarize long Reddit threads and comment chains',
      'Draft well-structured replies to complex discussions',
      'Extract key advice and recommendations from threads',
      'Research topics across multiple subreddit posts',
      'Identify the most upvoted and useful comments in a thread',
    ],
    examplePrompts: [
      'Summarize the top advice in this Reddit thread.',
      'What are the most recommended products in these comments?',
      'Draft a helpful reply to this question based on my expertise.',
      'Extract all the book recommendations mentioned in this thread.',
    ],
  },
  {
    slug: 'youtube',
    platform: 'YouTube',
    title: 'Prophet AI for YouTube',
    keyword: 'AI Chrome extension for YouTube',
    h1: 'Use Prophet AI with YouTube',
    description: 'Get more from YouTube with Prophet AI. Summarize video descriptions, analyze comments, research channels, and draft responses without leaving the platform.',
    tasks: [
      'Summarize video descriptions and metadata',
      'Analyze and summarize comment sections',
      'Draft comments and responses on videos',
      'Research channel content and posting patterns',
      'Extract key information from video descriptions and about pages',
      'Compare similar videos or channels',
    ],
    examplePrompts: [
      'Summarize what this video is about based on the title and description.',
      'What are the most common topics in the comments on this video?',
      'Draft a comment asking a follow-up question about the video topic.',
      'Extract all the links mentioned in this video description.',
    ],
  },
  {
    slug: 'stackoverflow',
    platform: 'Stack Overflow',
    title: 'Prophet AI for Stack Overflow',
    keyword: 'AI Chrome extension for Stack Overflow',
    h1: 'Use Prophet AI on Stack Overflow',
    description: 'Solve coding problems faster with Prophet AI on Stack Overflow. Understand answers, adapt code snippets, debug errors, and draft quality responses.',
    tasks: [
      'Explain accepted answers in simpler terms',
      'Adapt code snippets from answers to your specific use case',
      'Compare multiple answers and identify the best approach',
      'Debug error messages using context from Stack Overflow threads',
      'Draft well-formatted answers with code examples',
      'Identify outdated answers and suggest modern alternatives',
    ],
    examplePrompts: [
      'Explain this accepted answer in simple terms and adapt it for Python 3.12.',
      'Which answer on this page is the best approach for a production application?',
      'Adapt this code snippet to work with TypeScript and async/await.',
      'Draft a Stack Overflow answer for this question based on my approach.',
    ],
  },
  {
    slug: 'jira',
    platform: 'Jira',
    title: 'Prophet AI for Jira',
    keyword: 'AI Chrome extension for Jira',
    h1: 'Use Prophet AI with Jira',
    description: 'Manage Jira tickets more efficiently with Prophet AI. Draft issue descriptions, write acceptance criteria, summarize sprints, and navigate project boards with AI assistance.',
    tasks: [
      'Draft detailed issue descriptions with acceptance criteria',
      'Summarize sprint boards and backlog status',
      'Write user stories from brief requirements',
      'Generate test cases from issue descriptions',
      'Create bug reports with structured reproduction steps',
      'Summarize comments and discussions on tickets',
    ],
    examplePrompts: [
      'Write a user story with acceptance criteria based on this brief description.',
      'Create a bug report template from the error I am seeing on this page.',
      'Summarize the status of all tickets in this sprint board.',
      'Generate test cases for the feature described in this Jira ticket.',
    ],
  },
  {
    slug: 'shopify',
    platform: 'Shopify',
    title: 'Prophet AI for Shopify',
    keyword: 'AI Chrome extension for Shopify',
    h1: 'Use Prophet AI with Shopify',
    description: 'Manage your Shopify store more efficiently with Prophet AI. Write product descriptions, analyze orders, optimize listings, and handle customer communications.',
    tasks: [
      'Write compelling product descriptions that convert',
      'Optimize product titles and tags for SEO',
      'Draft responses to customer inquiries and reviews',
      'Analyze order data and identify trends on dashboard pages',
      'Generate collection descriptions and category pages',
      'Create marketing copy for promotions and sales',
    ],
    examplePrompts: [
      'Write a compelling product description for this item based on the specs on the page.',
      'Optimize the title and tags of this product for better search visibility.',
      'Draft a professional response to this customer review.',
      'Create a promotional email for the products in this collection.',
    ],
  },
]

export function getIntegrationBySlug(slug: string): IntegrationData | undefined {
  return integrations.find((i) => i.slug === slug)
}

export function getAllIntegrationSlugs(): string[] {
  return integrations.map((i) => i.slug)
}
